<x-filament-panels::page>
    <div class="flex  flex-wrap justify-between">
        <x-square-card 
            title="E-CODEVASF"
            url="https://www.php.net/"
            icon="heroicon-o-home" 
        />
        <x-square-card 
            title="E-CODEVASF"
            url="https://www.php.net/"
            icon="heroicon-o-home" 
        />
        <x-square-card 
            title="E-CODEVASF"
            url="https://www.php.net/"
            icon="heroicon-o-home" 
        />
        <x-square-card 
            title="E-CODEVASF"
            url="https://www.php.net/"
            icon="heroicon-o-home" 
        />
        <x-square-card 
            title="E-CODEVASF"
            url="https://www.php.net/"
            icon="heroicon-o-home" 
        />
        <x-square-card 
            title="E-CODEVASF"
            url="https://www.php.net/"
            icon="heroicon-o-home" 
        />
    </div>
</x-filament-panels::page>
